# Copyright (c) 2021 Enix, SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.
#
# Authors:
# Paul Laffitte <paul.laffitte@enix.fr>
# Alexandre Buisine <alexandre.buisine@enix.fr>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fifo-claim

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-marvelous-storage
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: fifo-pod

spec:
  initContainers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "rm -f /vol/fifo && mkfifo /vol/fifo"]
    name: mkfifo
    volumeMounts:
    - mountPath: /vol
      name: volume
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "while read line </vol/fifo; do echo $line; done"]
    name: read
    volumeMounts:
    - mountPath: /vol
      name: volume
  - image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "(while true; do for i in $(seq 0 100); do echo $i && sleep 0.1; done; done) > /vol/fifo"]
    name: write
    volumeMounts:
    - mountPath: /vol
      name: volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: fifo-claim
