apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-marvelous-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  # nodeSelector:
  #   multipath-debug: "true"
  containers:
  - image: alpine
    command: ["/bin/sh", "-c", "while sleep 1; do echo hello > /vol/test && ls -l /vol && cat /vol/test; done"]
    name: container
    volumeMounts:
    - mountPath: /vol
      name: volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: claim
